name: Backend pipeline

on:
  push:
    branches:
      - main

jobs: 
  simple-deployment-pipeline: # Name of the job
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Part4/Part4c_d/ex4.22_and_ex4.23/backend

    steps:
      - uses: actions/checkout@v4 # Copy the code from repository
      - uses: actions/setup-node@v4 # Set up Node to version 20
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install # Install all required dependencies
      
      # Now check for code style errors
      - name: Check style
        run: npm run lint

      # Run tests
      - name: Run tests
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
        run: npm run test
